// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZDPGAYJIXnMEDbDxrEGYkI1N4lWsGwLM',
    appId: '1:369474625505:web:9f8163af0208a573f23ca0',
    messagingSenderId: '369474625505',
    projectId: 'vallejo-mynotes',
    authDomain: 'vallejo-mynotes.firebaseapp.com',
    storageBucket: 'vallejo-mynotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR14qyl7CF7qRnaz-ItkQilLiLWNi1hGk',
    appId: '1:369474625505:android:b9ed11d7317f4b8bf23ca0',
    messagingSenderId: '369474625505',
    projectId: 'vallejo-mynotes',
    storageBucket: 'vallejo-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxYaNlQRDdYMSctE4m_FZJqmYL_FnMk90',
    appId: '1:369474625505:ios:c1f33fbead7db3eff23ca0',
    messagingSenderId: '369474625505',
    projectId: 'vallejo-mynotes',
    storageBucket: 'vallejo-mynotes.appspot.com',
    iosBundleId: 'mx.carlosvallejo.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxYaNlQRDdYMSctE4m_FZJqmYL_FnMk90',
    appId: '1:369474625505:ios:39ce1aed48922708f23ca0',
    messagingSenderId: '369474625505',
    projectId: 'vallejo-mynotes',
    storageBucket: 'vallejo-mynotes.appspot.com',
    iosBundleId: 'mx.carlosvallejo.mynotes.RunnerTests',
  );
}
